version: '3.7'
services:
  dynamodb:
    image:  adiaconu/movies-dynamodb
    container_name: dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./docker/dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/" 

  # app:
  #   image: serverlesspolska/serverless-framework
  #   depends_on: 
  #     - dynamodb
  #   command: sls offline --stage dev --region eu-west-1 --useDocker --dockerHost host.docker.internal --dockerHostServicePath ${PWD} --host 0.0.0.0 --noPrependStageInUrl
  #   privileged: true
  #   working_dir: /app
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - .:/app
  #     - "/var/run/docker.sock:/var/run/docker.sock"