version: '3.7'
services:
  dynamodb:
    image:  adiaconu/movies-dynamodb
    container_name: dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      -  ./docker/dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/" 

  # app-node:
  #   depends_on:
  #     - dynamodb-local
  #   image: banst/awscli #serverless image here
  #   container_name: app-node
  #   ports:
  #    - "8080:8080"
  #   environment:
  #     AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
  #     AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
  #   command:
  #     dynamodb describe-limits --endpoint-url http://dynamodb-local:8000 --region us-west-2

#load the seed data into MovieTable
#aws dynamodb batch-write-item --endpoint-url http://localhost:8000 --request-items file://ProductCatalog.json



# version: '3.1'

# services:

#   db:
#     image: mariadb
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root_password
#       MYSQL_DATABASE: mydb
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
    
#     volumes: 
#         - ./init:/docker-entrypoint-initdb.d

#   adminer:
#     image: adminer
#     restart: always
#     ports:
#       - 8080:8080